-- MySQL Script generated by MySQL Workbench
-- Mon Oct  1 11:36:05 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Comérage
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Comérage
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Comérage` DEFAULT CHARACTER SET utf8 ;
USE `Comérage` ;

-- -----------------------------------------------------
-- Table `Comérage`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Comérage`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(145) NOT NULL,
  `nickname` VARCHAR(45) NOT NULL,
  `password` VARCHAR(355) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Comérage`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Comérage`.`articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `body` VARCHAR(200) NOT NULL,
  `publication_date` DATETIME NOT NULL,
  `draft` TINYINT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_articles_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_articles_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `Comérage`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Comérage`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Comérage`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `body` VARCHAR(200) NOT NULL,
  `publication_date` DATETIME NOT NULL,
  `users_id` INT NOT NULL,
  `articles_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`, `articles_id`),
  INDEX `fk_comments_users1_idx` (`users_id` ASC),
  INDEX `fk_comments_articles1_idx` (`articles_id` ASC),
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `Comérage`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_articles1`
    FOREIGN KEY (`articles_id`)
    REFERENCES `Comérage`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Comérage`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Comérage`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(145) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Comérage`.`categories_has_articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Comérage`.`categories_has_articles` (
  `categories_id` INT NOT NULL,
  `articles_id` INT NOT NULL,
  PRIMARY KEY (`categories_id`, `articles_id`),
  INDEX `fk_categories_has_articles_articles1_idx` (`articles_id` ASC),
  INDEX `fk_categories_has_articles_categories_idx` (`categories_id` ASC),
  CONSTRAINT `fk_categories_has_articles_categories`
    FOREIGN KEY (`categories_id`)
    REFERENCES `Comérage`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categories_has_articles_articles1`
    FOREIGN KEY (`articles_id`)
    REFERENCES `Comérage`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
