const actionTypes = {
    CREATE_USER: 'CREATE_USER',
    LOGIN_USER: 'LOGIN_USER',
    CREATE_ARTICLE: 'CREATE_ARTICLE',
    UPDATE_ARTICLE: 'UPDATE_ARTICLE',
    DELETE_ARTICLE: 'DELETE_ARTICLE',
    CREATE_COMMENT: 'CREATE_COMMENT',
    DISPLAY_ARTICLES: 'DISPLAY_ARTICLES',
    STOP_DRAFT: 'STOP_DRAFT',
    DRAFT_ARTICLE: 'DRAFT_ARTICLE',
    DISPLAY_COMMENTS: 'DISPLAY_COMMENTS',
    DISPLAY_CATEGORIES: 'DISPLAY_CATEGORIES',
    DISPLAY_CATEGORIES_BY_ARTICLE: 'DISPLAY_CATEGORIES_BY_ARTICLE'
}

export default actionTypes;